server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Product
          uri: http://localhost:8081
          predicates:
            - Path=/products/** 
        - id: Return
          uri: http://localhost:8085
          predicates:
            - Path=/returns/**,/products/**
        - id: Information
          uri: http://localhost:8084
          predicates:
            - Path= /myOrders/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Product
          uri: http://Product:8080
          predicates:
            - Path=/products/** 
        - id: Return
          uri: http://Return:8080
          predicates:
            - Path=/returns/**,/products/**
        - id: Information
          uri: http://Information:8080
          predicates:
            - Path= /myOrders/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
